name: Build & Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: Windows
            eb_args: --win zip
            artifact: release/*.zip
          - os: macos-latest
            platform: macOS
            eb_args: --mac zip
            artifact: release/*.zip
          - os: ubuntu-latest
            platform: Linux
            eb_args: --linux tar.gz
            artifact: release/*.tar.gz

    runs-on: ${{ matrix.os }}
    name: Build for ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Linux build deps
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y rpm fakeroot

      - name: Build JS
        run: npm run build

      - name: Package app
        run: ./node_modules/.bin/electron-builder ${{ matrix.eb_args }} --publish=never
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          GITHUB_TOKEN: ""
          GH_TOKEN: ""

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact }}
